name: Deploy to Pantheon after sucessfull Check

on:
  workflow_run:
    workflows: ["PHP Coding Standards and PHP Standards"]
    types:
      - completed

jobs:
  verify-and-deploy:
    # Only run if PHP Checks succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Deploy with rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_USER: ${{ vars.DEPLOY_USER }}
          DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
        run: bash ./scripts/deploy.sh
