name: Deploy

on:
  workflow_run:
    workflows: ["PHP Checks"]    # trigger on one workflow's completion
    types: [completed]

jobs:
  verify-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Confirm Node workflow succeeded for this commit
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const headSha = context.payload.workflow_run.head_sha;
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner, repo, workflow_id: 'Node', per_page: 50
            });
            const match = runs.data.workflow_runs.find(r => r.head_sha === headSha);
            if (!match) {
              core.setFailed('No Node workflow run found for this commit SHA.');
            }
            if (match.conclusion !== 'success') {
              core.setFailed(`Node workflow conclusion: ${match.conclusion}`);
            }
      - name: Install dependencies
        run: npm install
      - name: Deploy with rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_USER: ${{ vars.DEPLOY_USER }}
          DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
        run: bash ./scripts/deploy.sh
