name: PHP Checks

on:
  push:
    branches: ["trunk", "main"]
  pull_request:
    branches: ["trunk"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - name: Validate Root composer.json and composer.lock
        run: composer validate --strict

      - name: Install Plugin dependencies for validation
        run: composer install --prefer-dist --no-progress --working-dir=mu-plugins/10up-plugin || true

      - name: Validate Plugin composer.json and composer.lock
        run: composer validate --strict --working-dir=mu-plugins/10up-plugin || true

      - name: Install Theme dependencies for validation
        run: composer install --prefer-dist --no-progress --working-dir=themes/10up-block-theme || true

      - name: Validate Theme composer.json and composer.lock
        run: composer validate --strict --working-dir=themes/10up-block-theme || true

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Root dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install Plugin dependencies
        run: composer install --prefer-dist --no-progress --working-dir=mu-plugins/10up-plugin

      - name: Install Theme dependencies
        run: composer install --prefer-dist --no-progress --working-dir=themes/10up-block-theme

      - name: Run PHPCS in mu-plugin
        run: composer lint -- wp-content/mu-plugins/10up-plugin/src

      - name: Run PHPCS in theme
        run: composer lint -- wp-content/themes/10up-block-theme

      - name: Run PHPStan
        run: composer static


