name: PHP Coding Standards and PHP Standards

on:
  push:
    branches: ["trunk", "main"]
  pull_request:
    branches: ["trunk"]

permissions:
  contents: read

jobs:
  setup:
    name: Setup & Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.composer-cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with Composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - name: Validate Root composer.json and composer.lock
        run: composer validate --strict

      - name: Validate Plugin composer.json and composer.lock
        run: |
          composer install --prefer-dist --no-progress --working-dir=mu-plugins/10up-plugin || true
          composer validate --strict --working-dir=mu-plugins/10up-plugin || true

      - name: Validate Theme composer.json and composer.lock
        run: |
          composer install --prefer-dist --no-progress --working-dir=themes/10up-block-theme || true
          composer validate --strict --working-dir=themes/10up-block-theme || true

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Root dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install Plugin dependencies
        run: composer install --prefer-dist --no-progress --working-dir=mu-plugins/10up-plugin

      - name: Install Theme dependencies
        run: composer install --prefer-dist --no-progress --working-dir=themes/10up-block-theme

  phpcs:
    name: Run PHPCS
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPCS in mu-plugin
        run: composer lint -- mu-plugins/10up-plugin/src

      - name: Run PHPCS in theme
        run: composer lint -- themes/10up-block-theme

  phpstan:
    name: Run PHPStan
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan
        run: composer static
